sudo: false
language: node_js
cache: yarn
notifications:
  email: false
node_js:
  - 'stable'
  - '7'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
before_script:
  - yarn run lint
  - yarn run flow
after_success:
  - yarn run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
